input { beats { port => 5044 } }
filter {
  if [message] =~ /^\{/ { json { source => "message" } }
  mutate { add_field => { "platform" => "three-s" } }
}
output {
  elasticsearch { hosts => ["http://elasticsearch:9200"] index => "three-s-events-%{+YYYY.MM.dd}" }
  stdout { codec => rubydebug }
}
